embed_dim: 256
hard_negative_weight: 10.0
image_encoder_name: microsoft/swin-base-patch4-window7-224
learning_rate: 0.0001
margin: 0.2
temperature: 0.07
text_encoder_name: roberta-large
use_hard_negatives: true
